image: registry.gitlab.com/markuman/dev/octave:4.2.0

variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - deploy

before_script:
- apk --update --no-cache add hiredis hiredis-dev
- cd mex/
- wget https://git.osuv.de/m/mUnittest/raw/branch/master/mUnittest.m

go-redis:
  stage: test
  tags:
    - docker
    - shared
  services:
    - name: redis:alpine
      alias: redis
  script:
    - octave-cli --eval 'quit(or(0, mUnittest("gitlabci")))'

pages:
  image: registry.gitlab.com/markuman/dotfiles/mdbooks:latest
  stage: deploy
  script:
  - cd docs && mdbook build && cd ..
  - mv docs/book/ public
  tags:
    - docker
    - shared
  artifacts:
    paths:
    - public
  only:
  - master
