image: mtmiller/octave:5.1.0

variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - deploy

go-redis:
  stage: test
  tags:
    - docker
    - shared
  services:
    - name: redis:alpine
      alias: redis
  script:
    - apt install libhiredis-dev libhiredis0.13 -y
    - make gitlab_build -C mex/
    - make gitlab_ci_test -C mex/

pages:
  image: registry.gitlab.com/markuman/dotfiles/mdbooks:latest
  stage: deploy
  script:
    - cd docs && /root/.cargo/bin/mdbook build && cd ..
    - mv docs/book/ public
  tags:
    - docker
    - shared
  artifacts:
    paths:
      - public
  only:
    - master
