image: registry.gitlab.com/markuman/dev/octave:4.2.0

variables:
  DOCKER_DRIVER: overlay

stages:
  - test

before_script:
- apk --update --no-cache add hiredis hiredis-dev
- wget https://raw.githubusercontent.com/markuman/mUnittest/master/mUnittest.m

go-redis:
  stage: test
  tags:
    - docker
    - shared
  services:
    - name: redis:alpine
      alias: redis
  script:
    - cd mex/
    - octave-cli --eval 'quit(or(0, mUnittest("gitlabci")))'
