image: registry.gitlab.com/markuman/dev/octave:4.2.0

variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - deploy

go-redis:
  stage: test
  tags:
    - docker
    - shared
  services:
    - name: redis:alpine
      alias: redis
  script:
    - apk --update --no-cache add hiredis hiredis-dev make
    - make build -C mex/
    - make gitlab_ci_test -C mex/

pages:
  image: registry.gitlab.com/markuman/dotfiles/mdbooks:latest
  stage: deploy
  script:
  - cd docs && /root/.cargo/bin/mdbook build && cd ..
  - mv docs/book/ public
  tags:
    - docker
    - shared
  artifacts:
    paths:
    - public
  only:
  - master
